name: 'silver_vnstock'
version: '1.0.0'
config-version: 2

profile: 'spark'

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  silver_vnstock:
    +materialized: table
    +schema: silver
